# Generated by Django 2.1.2 on 2018-10-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('lives_in', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('place_of_meeting', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
    ]
