# Generated by Django 2.1.2 on 2018-10-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
